spring.application.name=AccademiJava

spring.datasource.url=jdbc:postgresql://localhost:5432/accademi
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
#server.port=8081