spring.application.name=AccademiJava

spring.datasource.url=jdbc:postgresql://localhost:5432/accademi
spring.datasource.username=postgres
spring.datasource.password=root

# ? Disabilita Hibernate auto schema
spring.jpa.hibernate.ddl-auto=none

# ? Esegui sempre SQL all'avvio
spring.sql.init.mode=always

# (opzionale ma consigliato)
spring.jpa.show-sql=false